---
- name: System aktualisieren
  ansible.builtin.dnf:
    name: '*'
    state: latest
    update_cache: true

- name: Wichtige Basistools installieren
  ansible.builtin.dnf:
    name:
      - curl
      - git
      - firewalld
      - unzip
      - auditd
    state: present

- name: Firewalld starten und aktivieren
  ansible.builtin.systemd:
    name: firewalld
    state: started
    enabled: true

# --- CIS HARDENING ERWEITERUNGEN (Punkt 3) ---

- name: SSH Root-Login absichern (PermitRootLogin prohibit-password)
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PermitRootLogin'
    line: 'PermitRootLogin prohibit-password'
    state: present
  notify: restart sshd

- name: SSH Password Authentication deaktivieren (Key-only)
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication'
    line: 'PasswordAuthentication no'
    state: present
  notify: restart sshd

- name: Sichere Sysctl-Netzwerkparameter setzen (IP Spoofing & SYN-Flood Schutz)
  ansible.builtin.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_set: true
    state: present
    reload: true
  loop:
    - { key: 'net.ipv4.conf.all.rp_filter', value: '1' }
    - { key: 'net.ipv4.tcp_syncookies', value: '1' }
    - { key: 'net.ipv4.conf.all.accept_source_route', value: '0' }
    - { key: 'net.ipv4.conf.all.accept_redirects', value: '0' }

- name: Auditd Dienst aktivieren und starten
  ansible.builtin.systemd:
    name: auditd
    state: started
    enabled: true
