---
- name: Create Grafana dashboard directory
  file:
    path: /etc/grafana/provisioning/dashboards
    state: directory
    owner: root
    group: grafana
    mode: '0750'

- name: Copy provisioning configuration for dashboards
  copy:
    content: |
      apiVersion: 1
      providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /etc/grafana/dashboards
    dest: /etc/grafana/provisioning/dashboards/dashboard.yaml

- name: Ensure target dashboard folder exists
  file:
    path: /etc/grafana/dashboards
    state: directory
    owner: root
    group: grafana
    mode: '0750'

- name: Copy SOC Dashboard JSON to Grafana
  copy:
    src: dashboards/soc-overview.json
    dest: /etc/grafana/dashboards/soc-overview.json
    owner: root
    group: grafana
    mode: '0640'
  notify: restart grafana
