---

- name: Grafana RPM Key importieren
  ansible.builtin.rpm_key:
    state: present
    key: https://rpm.grafana.com/gpg.key

- name: Grafana Repository hinzufügen
  ansible.builtin.yum_repository:
    name: grafana
    description: Grafana Repository
    baseurl: https://rpm.grafana.com
    gpgcheck: yes

- name: Grafana installieren
  ansible.builtin.dnf:
    name: grafana
    state: present

- name: Grafana Dienst starten und aktivieren
  ansible.builtin.systemd:
    name: grafana-server
    state: started
    enabled: true

- name: Create Grafana dashboard directory
  file:
    path: /etc/grafana/provisioning/dashboards
    state: directory
    owner: root
    group: grafana
    mode: '0750'

- name: Copy provisioning configuration for dashboards
  copy:
    content: |
      apiVersion: 1
      providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /etc/grafana/dashboards
    dest: /etc/grafana/provisioning/dashboards/dashboard.yaml

- name: Ensure target dashboard folder exists
  file:
    path: /etc/grafana/dashboards
    state: directory
    owner: root
    group: grafana
    mode: '0750'

- name: Copy SOC Dashboard JSON to Grafana
  copy:
    src: dashboards/soc-overview.json
    dest: /etc/grafana/dashboards/soc-overview.json
    owner: root
    group: grafana
    mode: '0640'
  notify: restart grafana
