all:
  children:
    soc_hub:
      hosts:
        soc_server:
          ansible_host: "{{ lookup('env', 'SOC_HOST_IP') | default('192.168.1.100', true) }}" # Fallback auf lokale IP
          ansible_user: root
          ansible_ssh_private_key_file: "~/.ssh/id_rsa"
