---
# Unkritische globale Variablen
environment_name: "production"
wireguard_subnet: "10.100.0.0/24"
soc_hub_ip: "192.168.1.100" # Wird dynamisch vom Master-Skript überschrieben
backup_lab_ip: "192.168.1.200"
