---
environment_name: "production"
wireguard_subnet: "10.100.0.0/24"
soc_hub_ip: "192.168.1.100"
backup_lab_ip: "192.168.56.50"

# Enterprise Secrets Management: Striktes Vault-Mapping (Keine Plaintext-Keys)
wg_hub_privkey: "{{ vault_wg_hub_privkey }}"
node_public_key: "{{ vault_node_public_key }}"
