---
- name: Prometheus Gruppe erstellen
  ansible.builtin.group:
    name: prometheus
    system: true

- name: Prometheus Benutzer erstellen
  ansible.builtin.user:
    name: prometheus
    system: true
    shell: /sbin/nologin
    group: prometheus

- name: Prometheus herunterladen und entpacken
  ansible.builtin.unarchive:
    src: "https://github.com/prometheus/prometheus/releases/download/v2.53.0/prometheus-2.53.0.linux-amd64.tar.gz"
    dest: "/tmp/"
    remote_src: yes

- name: Prometheus Binärdateien verschieben
  ansible.builtin.copy:
    src: "/tmp/prometheus-2.53.0.linux-amd64/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: '0755'
    remote_src: yes
  loop:
    - prometheus
    - promtool

- name: Prometheus Verzeichnisse erstellen
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
    mode: '0755'
  loop:
    - /etc/prometheus
    - /var/lib/prometheus

- name: Prometheus Alert-Rules rendern
  ansible.builtin.template:
    src: alert_rules.yml.j2
    dest: /etc/prometheus/alert_rules.yml
    owner: prometheus
    group: prometheus
    mode: '0644'
  notify: Restart Prometheus

- name: Prometheus Konfiguration rendern
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus
    mode: '0644'
  notify: Restart Prometheus

- name: Systemd Service für Prometheus einrichten
  ansible.builtin.copy:
    dest: /etc/systemd/system/prometheus.service
    content: |
      [Unit]
      Description=Prometheus
      Wants=network-online.target
      After=network-online.target

      [Service]
      User=prometheus
      Group=prometheus
      Type=simple
      ExecStart=/usr/local/bin/prometheus \
        --config.file=/etc/prometheus/prometheus.yml \
        --storage.tsdb.path=/var/lib/prometheus/ \
        --storage.tsdb.retention.time=30d \
        --web.console.templates=/etc/prometheus/consoles \
        --web.console.libraries=/etc/prometheus/console_libraries

      [Install]
      WantedBy=multi-user.target
  notify: Reload systemd

- name: Prometheus aktivieren und starten
  ansible.builtin.systemd:
    name: prometheus
    enabled: true
    state: started
