---
- name: firewalld installieren und aktivieren
  ansible.builtin.dnf:
    name: firewalld
    state: present

- name: firewalld Service starten
  ansible.builtin.systemd:
    name: firewalld
    state: started
    enabled: yes

- name: WireGuard VPN-Tunnel als Trusted deklarieren (Zero-Trust mTLS)
  ansible.posix.firewalld:
    zone: trusted
    interface: wg0
    permanent: yes
    state: enabled
    immediate: yes

- name: Benötigte Ports für externes Management freigeben
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  loop:
    - 22/tcp   # SSH (eingeschränkt via Terraform)
    - 3000/tcp # Grafana Web-UI
